
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 28 14:41:42 CST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int Dim = 2;
  public static final int EOF = 0;
}

