
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 22 19:21:32 CST 2014
//----------------------------------------------------

package compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Input = 64;
  public static final int Return = 8;
  public static final int ParDer = 63;
  public static final int Menor = 65;
  public static final int Coma = 76;
  public static final int LlaveIzq = 61;
  public static final int Punto = 59;
  public static final int Print = 58;
  public static final int Char = 32;
  public static final int Concatenacion = 24;
  public static final int EndWhile = 13;
  public static final int For = 45;
  public static final int Div = 7;
  public static final int Mult = 6;
  public static final int DosPuntos = 3;
  public static final int Else = 48;
  public static final int ByRef = 20;
  public static final int Resta = 5;
  public static final int EndLine = 74;
  public static final int Dim = 17;
  public static final int Suma = 4;
  public static final int com = 40;
  public static final int MenorIgual = 68;
  public static final int Main = 18;
  public static final int EndIf = 51;
  public static final int String = 34;
  public static final int Structs = 9;
  public static final int Do = 43;
  public static final int Exit = 30;
  public static final int Private = 12;
  public static final int DiviEntera = 25;
  public static final int Imp = 28;
  public static final int Function = 80;
  public static final int EndCase = 15;
  public static final int End = 50;
  public static final int ParIzq = 62;
  public static final int Case = 31;
  public static final int Step = 29;
  public static final int GuionBajo = 26;
  public static final int Or = 72;
  public static final int And = 71;
  public static final int Ch = 38;
  public static final int Call = 77;
  public static final int EndSub = 52;
  public static final int Mayor = 66;
  public static final int If = 42;
  public static final int Xor = 73;
  public static final int Id = 75;
  public static final int LlaveDer = 60;
  public static final int MayorIgual = 69;
  public static final int EndType = 54;
  public static final int EOF = 0;
  public static final int SelectCase = 41;
  public static final int Asigna = 78;
  public static final int Double = 22;
  public static final int Type = 37;
  public static final int Integer = 33;
  public static final int ByVal = 19;
  public static final int EndFunction = 53;
  public static final int EndSelect = 14;
  public static final int error = 1;
  public static final int Next = 56;
  public static final int To = 47;
  public static final int Potencia = 2;
  public static final int ExitFor = 11;
  public static final int Float = 21;
  public static final int As = 16;
  public static final int Select = 23;
  public static final int Eqv = 27;
  public static final int Entero = 36;
  public static final int Sub = 57;
  public static final int Loop = 55;
  public static final int EndFor = 10;
  public static final int Distinto = 67;
  public static final int Not = 70;
  public static final int ElseIf = 49;
  public static final int str = 39;
  public static final int Then = 46;
  public static final int TipoBoolean = 79;
  public static final int While = 44;
  public static final int Boolean = 35;
}

