
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 07 16:49:59 CST 2014
//----------------------------------------------------

package compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Return = 71;
  public static final int ParDer = 42;
  public static final int Menos = 49;
  public static final int Menor = 43;
  public static final int LlaveIzq = 67;
  public static final int Coma = 64;
  public static final int Print = 40;
  public static final int Char = 10;
  public static final int Concatenacion = 63;
  public static final int Funtion = 9;
  public static final int EndWhile = 30;
  public static final int For = 21;
  public static final int Entre = 52;
  public static final int Div = 6;
  public static final int Mult = 5;
  public static final int DosPuntos = 62;
  public static final int Else = 27;
  public static final int Mas = 50;
  public static final int Resta = 4;
  public static final int Dim = 8;
  public static final int EndLine = 60;
  public static final int Suma = 3;
  public static final int MenorIgual = 47;
  public static final int EndIf = 29;
  public static final int String = 14;
  public static final int Structs = 37;
  public static final int Do = 19;
  public static final int Exit = 35;
  public static final int Private = 39;
  public static final int DiviEntera = 53;
  public static final int Imp = 59;
  public static final int Function = 70;
  public static final int End = 28;
  public static final int ParIzq = 41;
  public static final int Case = 24;
  public static final int GuionBajo = 68;
  public static final int And = 55;
  public static final int Ch = 17;
  public static final int Or = 56;
  public static final int Mayor = 44;
  public static final int If = 18;
  public static final int Xor = 57;
  public static final int LlaveDer = 66;
  public static final int Id = 61;
  public static final int MayorIgual = 48;
  public static final int EOF = 0;
  public static final int SelectCase = 25;
  public static final int Asigna = 65;
  public static final int Double = 11;
  public static final int Integer = 13;
  public static final int EndSelect = 32;
  public static final int error = 1;
  public static final int Next = 34;
  public static final int To = 26;
  public static final int Potencia = 46;
  public static final int ExitFor = 36;
  public static final int Float = 12;
  public static final int As = 7;
  public static final int Select = 23;
  public static final int Eqv = 58;
  public static final int Por = 51;
  public static final int Entero = 16;
  public static final int Sub = 38;
  public static final int Loop = 33;
  public static final int EndFor = 31;
  public static final int Distinto = 45;
  public static final int Not = 54;
  public static final int Igual = 2;
  public static final int Then = 22;
  public static final int TipoBoolean = 69;
  public static final int While = 20;
  public static final int Boolean = 15;
}

