
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 05 11:33:18 CST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EndFor = 27;
  public static final int Ch = 16;
  public static final int Entero = 15;
  public static final int Coma = 51;
  public static final int End = 24;
  public static final int Double = 10;
  public static final int ParIzq = 34;
  public static final int If = 17;
  public static final int Id = 48;
  public static final int Potencia = 39;
  public static final int Sub = 31;
  public static final int Mas = 43;
  public static final int Menos = 42;
  public static final int Menor = 36;
  public static final int Else = 23;
  public static final int Asignacion = 52;
  public static final int Por = 44;
  public static final int Mayor = 37;
  public static final int Then = 21;
  public static final int Concatenacion = 50;
  public static final int Structs = 30;
  public static final int LlaveDer = 53;
  public static final int While = 19;
  public static final int To = 22;
  public static final int Float = 11;
  public static final int For = 20;
  public static final int EOF = 0;
  public static final int DosPuntos = 49;
  public static final int ParDer = 35;
  public static final int Function = 57;
  public static final int error = 1;
  public static final int Funtion = 8;
  public static final int Distinto = 38;
  public static final int DiviEntera = 46;
  public static final int Entre = 45;
  public static final int As = 6;
  public static final int Integer = 12;
  public static final int Private = 32;
  public static final int Mult = 4;
  public static final int Char = 9;
  public static final int Div = 5;
  public static final int Print = 33;
  public static final int Do = 18;
  public static final int EndLine = 47;
  public static final int EndWhile = 26;
  public static final int MenorIgual = 40;
  public static final int Dim = 7;
  public static final int String = 13;
  public static final int TipoBoolean = 56;
  public static final int EndIf = 25;
  public static final int Resta = 3;
  public static final int MayorIgual = 41;
  public static final int Boolean = 14;
  public static final int Suma = 2;
  public static final int Next = 29;
  public static final int Loop = 28;
  public static final int GuionBajo = 55;
  public static final int LlaveIzq = 54;
}

