/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>src/compiladores/Visual.flex</tt>
 */
class Visual implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int str = 2;
  public static final int com = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\64\1\47\1\75\1\75\1\47\22\0\1\63\1\0\1\61"+
    "\3\0\1\60\1\74\1\71\1\72\1\67\1\66\1\54\1\65\1\0"+
    "\1\70\12\50\1\53\1\0\1\55\1\46\1\56\2\0\1\1\1\3"+
    "\1\11\1\14\1\21\1\26\2\45\1\23\2\45\1\33\1\45\1\35"+
    "\1\42\1\40\2\45\1\27\1\37\2\45\1\25\1\43\2\45\1\0"+
    "\1\62\1\0\1\57\1\73\1\0\1\7\1\20\1\30\1\22\1\6"+
    "\1\24\1\32\1\12\1\15\2\45\1\5\1\16\1\10\1\4\1\34"+
    "\1\44\1\13\1\2\1\31\1\17\1\41\1\45\1\36\2\45\1\51"+
    "\1\0\1\52\7\0\1\75\u1fa2\0\1\75\1\75\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\22\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\31\1\33\1\34\1\35\4\2"+
    "\1\36\7\2\1\37\14\2\1\40\2\2\1\41\1\2"+
    "\1\0\1\42\1\43\1\44\1\45\1\46\4\2\1\47"+
    "\1\2\1\50\1\2\1\51\1\2\1\52\2\2\1\53"+
    "\3\2\1\54\3\2\1\55\3\2\1\56\1\0\1\2"+
    "\1\57\1\60\1\2\1\61\1\0\1\62\7\2\1\63"+
    "\1\64\1\65\1\66\2\2\1\0\2\2\4\0\1\2"+
    "\1\0\1\2\1\67\1\70\4\2\1\71\1\2\1\0"+
    "\1\2\1\72\1\73\3\0\1\2\1\0\2\2\1\74"+
    "\1\75\2\2\1\0\1\76\1\0\1\77\1\0\1\100"+
    "\1\0\1\101\1\2\1\102\1\103\1\104\2\0\1\100"+
    "\1\105\1\106\1\0\1\107";

  private static int [] zzUnpackAction() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\u0136\0\u0174\0\u01b2"+
    "\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2"+
    "\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\272\0\u0554"+
    "\0\u0592\0\u05d0\0\272\0\272\0\272\0\u060e\0\u064c\0\272"+
    "\0\272\0\272\0\272\0\272\0\272\0\272\0\272\0\272"+
    "\0\272\0\272\0\272\0\272\0\272\0\272\0\u068a\0\u06c8"+
    "\0\272\0\u0136\0\u0706\0\u0744\0\u0782\0\u07c0\0\u07fe\0\u083c"+
    "\0\u087a\0\u08b8\0\u08f6\0\u0934\0\u0972\0\u09b0\0\u0136\0\u09ee"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde"+
    "\0\u0c1c\0\u0c5a\0\u0c98\0\u0136\0\u0cd6\0\u0d14\0\u0136\0\u0d52"+
    "\0\u0d90\0\272\0\272\0\272\0\272\0\u0136\0\u0dce\0\u0e0c"+
    "\0\u0e4a\0\u0e88\0\u0136\0\u0ec6\0\u0f04\0\u0f42\0\u0136\0\u0f80"+
    "\0\u0136\0\u0fbe\0\u0ffc\0\u0136\0\u103a\0\u1078\0\u10b6\0\u0136"+
    "\0\u10f4\0\u1132\0\u1170\0\u0136\0\u11ae\0\u11ec\0\u122a\0\u0136"+
    "\0\u1268\0\u12a6\0\u0136\0\u0136\0\u12e4\0\u0136\0\u1322\0\u1360"+
    "\0\u139e\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512\0\u0136"+
    "\0\u0136\0\u0136\0\u0136\0\u1550\0\u158e\0\u15cc\0\u160a\0\u1648"+
    "\0\u1686\0\u16c4\0\u1702\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u0136"+
    "\0\u0136\0\u1838\0\u1876\0\u18b4\0\u18f2\0\u0136\0\u1930\0\u196e"+
    "\0\u19ac\0\u0136\0\272\0\u19ea\0\u1a28\0\u1a66\0\u1aa4\0\u1ae2"+
    "\0\u1b20\0\u1b5e\0\u0136\0\u0136\0\u1b9c\0\u1bda\0\u1c18\0\u0136"+
    "\0\u1c56\0\272\0\u1c94\0\u0136\0\u1cd2\0\u0136\0\u1d10\0\u0136"+
    "\0\u0136\0\272\0\u1d4e\0\u1d8c\0\272\0\u0136\0\272\0\u1dca"+
    "\0\272";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\5\6\1\10\2\6\1\11"+
    "\4\6\1\12\1\6\1\13\1\14\1\15\1\16\1\17"+
    "\1\6\1\20\1\6\1\21\1\6\1\22\1\6\1\23"+
    "\1\24\1\6\1\25\1\26\2\6\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\2\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\0\47\55\1\0\11\55\1\56"+
    "\1\57\12\55\1\0\47\55\1\60\24\55\1\61\100\0"+
    "\1\6\1\62\5\6\1\63\35\6\2\0\1\6\22\0"+
    "\1\6\3\0\45\6\2\0\1\6\22\0\1\6\3\0"+
    "\3\6\1\64\41\6\2\0\1\6\22\0\1\6\3\0"+
    "\6\6\1\65\2\6\1\66\33\6\2\0\1\6\22\0"+
    "\1\6\3\0\3\6\1\67\10\6\1\70\30\6\2\0"+
    "\1\6\22\0\1\6\3\0\4\6\1\71\2\6\1\72"+
    "\25\6\1\73\5\6\1\74\1\6\2\0\1\6\22\0"+
    "\1\6\3\0\7\6\1\75\5\6\1\76\5\6\1\77"+
    "\21\6\2\0\1\6\22\0\1\6\3\0\6\6\1\100"+
    "\36\6\2\0\1\6\22\0\1\6\3\0\11\6\1\101"+
    "\33\6\2\0\1\6\22\0\1\6\3\0\3\6\1\102"+
    "\1\103\11\6\1\104\26\6\2\0\1\6\22\0\1\6"+
    "\3\0\5\6\1\105\10\6\1\106\11\6\1\107\14\6"+
    "\2\0\1\6\22\0\1\6\3\0\12\6\1\110\32\6"+
    "\2\0\1\6\22\0\1\6\3\0\3\6\1\111\41\6"+
    "\2\0\1\6\22\0\1\6\3\0\3\6\1\112\1\6"+
    "\1\113\37\6\2\0\1\6\22\0\1\6\3\0\3\6"+
    "\1\114\5\6\1\115\33\6\2\0\1\6\22\0\1\6"+
    "\3\0\12\6\1\116\32\6\2\0\1\6\22\0\1\6"+
    "\3\0\12\6\1\117\32\6\2\0\1\6\22\0\1\6"+
    "\3\0\3\6\1\120\41\6\2\0\1\6\22\0\1\6"+
    "\51\0\1\30\76\0\1\31\32\0\1\121\136\0\1\122"+
    "\7\0\1\123\65\0\1\124\110\0\1\125\63\0\1\60"+
    "\27\0\21\6\1\126\23\6\2\0\1\6\22\0\1\6"+
    "\3\0\3\6\1\127\41\6\2\0\1\6\22\0\1\6"+
    "\3\0\1\6\1\130\43\6\2\0\1\6\22\0\1\6"+
    "\3\0\6\6\1\131\36\6\2\0\1\6\22\0\1\6"+
    "\3\0\16\6\1\132\26\6\2\0\1\6\22\0\1\6"+
    "\3\0\15\6\1\133\27\6\2\0\1\6\22\0\1\6"+
    "\3\0\1\6\1\134\43\6\2\0\1\6\22\0\1\6"+
    "\3\0\21\6\1\135\23\6\2\0\1\6\22\0\1\6"+
    "\3\0\14\6\1\136\30\6\2\0\1\6\22\0\1\6"+
    "\3\0\40\6\1\137\4\6\2\0\1\6\22\0\1\6"+
    "\3\0\30\6\1\140\14\6\2\0\1\6\22\0\1\6"+
    "\3\0\33\6\1\141\11\6\2\0\1\6\22\0\1\6"+
    "\3\0\4\6\1\142\40\6\2\0\1\6\22\0\1\6"+
    "\3\0\14\6\1\143\30\6\2\0\1\6\22\0\1\6"+
    "\3\0\12\6\1\144\32\6\2\0\1\6\22\0\1\6"+
    "\3\0\3\6\1\145\41\6\2\0\1\6\22\0\1\6"+
    "\3\0\7\6\1\146\35\6\2\0\1\6\22\0\1\6"+
    "\3\0\4\6\1\147\40\6\2\0\1\6\22\0\1\6"+
    "\3\0\17\6\1\150\25\6\2\0\1\6\22\0\1\6"+
    "\3\0\12\6\1\151\32\6\2\0\1\6\22\0\1\6"+
    "\3\0\16\6\1\152\26\6\2\0\1\6\22\0\1\6"+
    "\3\0\3\6\1\153\41\6\2\0\1\6\22\0\1\6"+
    "\3\0\30\6\1\154\14\6\2\0\1\6\22\0\1\6"+
    "\3\0\35\6\1\155\7\6\2\0\1\6\22\0\1\6"+
    "\3\0\5\6\1\156\37\6\2\0\1\6\22\0\1\6"+
    "\3\0\14\6\1\157\30\6\2\0\1\6\22\0\1\6"+
    "\3\0\12\6\1\160\32\6\2\0\1\6\22\0\1\6"+
    "\10\0\1\161\70\0\4\6\1\162\40\6\2\0\1\6"+
    "\22\0\1\6\3\0\5\6\1\163\37\6\2\0\1\6"+
    "\22\0\1\6\3\0\12\6\1\164\32\6\2\0\1\6"+
    "\22\0\1\6\3\0\17\6\1\165\25\6\2\0\1\6"+
    "\22\0\1\6\3\0\5\6\1\166\37\6\2\0\1\6"+
    "\22\0\1\6\3\0\45\6\2\0\1\6\12\0\1\167"+
    "\7\0\1\6\3\0\30\6\1\170\14\6\2\0\1\6"+
    "\22\0\1\6\3\0\5\6\1\171\37\6\2\0\1\6"+
    "\22\0\1\6\3\0\1\6\1\152\43\6\2\0\1\6"+
    "\22\0\1\6\3\0\4\6\1\172\40\6\2\0\1\6"+
    "\22\0\1\6\3\0\6\6\1\173\36\6\2\0\1\6"+
    "\22\0\1\6\3\0\27\6\1\174\15\6\2\0\1\6"+
    "\22\0\1\6\3\0\5\6\1\175\37\6\2\0\1\6"+
    "\22\0\1\6\3\0\14\6\1\176\1\6\1\177\26\6"+
    "\2\0\1\6\22\0\1\6\3\0\5\6\1\200\37\6"+
    "\2\0\1\6\22\0\1\6\3\0\33\6\1\201\11\6"+
    "\2\0\1\6\22\0\1\6\3\0\30\6\1\202\14\6"+
    "\2\0\1\6\22\0\1\6\3\0\7\6\1\203\35\6"+
    "\2\0\1\6\22\0\1\6\3\0\7\6\1\204\30\6"+
    "\1\205\4\6\2\0\1\6\22\0\1\6\33\0\1\206"+
    "\45\0\5\6\1\207\37\6\2\0\1\6\22\0\1\6"+
    "\3\0\4\6\1\210\40\6\2\0\1\6\22\0\1\6"+
    "\25\0\1\211\1\0\1\212\1\213\1\214\33\0\1\167"+
    "\13\0\25\6\1\215\17\6\2\0\1\6\12\0\1\216"+
    "\7\0\1\6\3\0\31\6\1\217\13\6\2\0\1\6"+
    "\22\0\1\6\3\0\5\6\1\220\37\6\2\0\1\6"+
    "\22\0\1\6\3\0\30\6\1\221\14\6\2\0\1\6"+
    "\22\0\1\6\3\0\30\6\1\222\14\6\2\0\1\6"+
    "\22\0\1\6\3\0\27\6\1\223\15\6\2\0\1\6"+
    "\22\0\1\6\3\0\7\6\1\224\35\6\2\0\1\6"+
    "\22\0\1\6\3\0\27\6\1\225\15\6\2\0\1\6"+
    "\22\0\1\6\3\0\30\6\1\226\14\6\2\0\1\6"+
    "\22\0\1\6\3\0\6\6\1\227\36\6\2\0\1\6"+
    "\22\0\1\6\15\0\1\230\63\0\6\6\1\231\36\6"+
    "\2\0\1\6\22\0\1\6\3\0\5\6\1\232\37\6"+
    "\2\0\1\6\22\0\1\6\26\0\1\233\63\0\1\234"+
    "\67\0\1\235\77\0\1\236\70\0\3\6\1\237\41\6"+
    "\2\0\1\6\22\0\1\6\30\0\1\240\34\0\1\216"+
    "\13\0\5\6\1\241\37\6\2\0\1\6\22\0\1\6"+
    "\3\0\14\6\1\242\30\6\2\0\1\6\22\0\1\6"+
    "\3\0\30\6\1\243\14\6\2\0\1\6\22\0\1\6"+
    "\3\0\31\6\1\244\13\6\2\0\1\6\22\0\1\6"+
    "\3\0\30\6\1\245\14\6\2\0\1\6\22\0\1\6"+
    "\3\0\30\6\1\246\14\6\2\0\1\6\22\0\1\6"+
    "\11\0\1\247\67\0\7\6\1\250\35\6\2\0\1\6"+
    "\22\0\1\6\17\0\1\251\73\0\1\252\67\0\1\253"+
    "\71\0\12\6\1\254\32\6\2\0\1\6\22\0\1\6"+
    "\6\0\1\255\72\0\12\6\1\256\32\6\2\0\1\6"+
    "\22\0\1\6\3\0\3\6\1\257\41\6\2\0\1\6"+
    "\22\0\1\6\3\0\1\6\1\260\43\6\2\0\1\6"+
    "\22\0\1\6\3\0\5\6\1\261\37\6\2\0\1\6"+
    "\22\0\1\6\54\0\1\262\30\0\1\263\76\0\1\264"+
    "\102\0\1\265\63\0\7\6\1\266\35\6\2\0\1\6"+
    "\22\0\1\6\10\0\1\267\117\0\1\270\76\0\1\271"+
    "\44\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7688];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\22\1\1\11\3\1\3\11\2\1\17\11"+
    "\2\1\1\11\37\1\1\0\4\11\33\1\1\0\5\1"+
    "\1\0\16\1\1\0\2\1\4\0\1\1\1\0\11\1"+
    "\1\0\2\1\1\11\3\0\1\1\1\0\6\1\1\0"+
    "\1\1\1\0\1\11\1\0\1\1\1\0\4\1\1\11"+
    "\2\0\1\11\1\1\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	String st;
	private Symbol symbol(int type) {
    	return new Symbol(type, yyline, yycolumn);
  	}
  	private Symbol symbol(int type, Object value) {
    	return new Symbol(type, yyline, yycolumn, value);
  	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Visual(java.io.Reader in) {
  	st = "";
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Visual(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 176) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("Error Lexico. Fila: "+ (yyline+1) +" Columna: " + (yycolumn+1) );
          }
        case 72: break;
        case 2: 
          { return symbol(sym.Id);
          }
        case 73: break;
        case 3: 
          { return symbol(sym.Asignacion);
          }
        case 74: break;
        case 4: 
          { return symbol(sym.EndLine);
          }
        case 75: break;
        case 5: 
          { return symbol(sym.Entero);
          }
        case 76: break;
        case 6: 
          { return symbol(sym.LlaveDer);
          }
        case 77: break;
        case 7: 
          { return symbol(sym.LlaveIzq);
          }
        case 78: break;
        case 8: 
          { return symbol(sym.DosPuntos);
          }
        case 79: break;
        case 9: 
          { return symbol(sym.Coma);
          }
        case 80: break;
        case 10: 
          { return symbol(sym.Menor);
          }
        case 81: break;
        case 11: 
          { return symbol(sym.Mayor);
          }
        case 82: break;
        case 12: 
          { return symbol(sym.Potencia);
          }
        case 83: break;
        case 13: 
          { return symbol(sym.Concatenacion);
          }
        case 84: break;
        case 14: 
          { yybegin(str);
          }
        case 85: break;
        case 15: 
          { return symbol(sym.DiviEntera);
          }
        case 86: break;
        case 16: 
          { 
          }
        case 87: break;
        case 17: 
          { return symbol(sym.Menos);
          }
        case 88: break;
        case 18: 
          { return symbol(sym.Suma);
          }
        case 89: break;
        case 19: 
          { return symbol(sym.Mult);
          }
        case 90: break;
        case 20: 
          { return symbol(sym.Div);
          }
        case 91: break;
        case 21: 
          { return symbol(sym.ParIzq);
          }
        case 92: break;
        case 22: 
          { return symbol(sym.ParDer);
          }
        case 93: break;
        case 23: 
          { return symbol(sym.GuionBajo);
          }
        case 94: break;
        case 24: 
          { yybegin(com);
          }
        case 95: break;
        case 25: 
          { st+=yytext();
          }
        case 96: break;
        case 26: 
          { System.out.println("String: " + st);st="";yybegin(YYINITIAL);
          }
        case 97: break;
        case 27: 
          { System.out.println("Comentario");yybegin(YYINITIAL);
          }
        case 98: break;
        case 28: 
          { System.out.println("String");yybegin(YYINITIAL);
          }
        case 99: break;
        case 29: 
          { return symbol(sym.As);
          }
        case 100: break;
        case 30: 
          { return symbol(sym.Do);
          }
        case 101: break;
        case 31: 
          { return symbol(sym.If);
          }
        case 102: break;
        case 32: 
          { return symbol(sym.To);
          }
        case 103: break;
        case 33: 
          { return symbol(sym.Or);
          }
        case 104: break;
        case 34: 
          { return symbol(sym.MenorIgual);
          }
        case 105: break;
        case 35: 
          { return symbol(sym.Distinto);
          }
        case 106: break;
        case 36: 
          { return symbol(sym.MayorIgual);
          }
        case 107: break;
        case 37: 
          { st+="\"";
          }
        case 108: break;
        case 38: 
          { return symbol(sym.And);
          }
        case 109: break;
        case 39: 
          { return symbol(sym.Dim);
          }
        case 110: break;
        case 40: 
          { return symbol(sym.End);
          }
        case 111: break;
        case 41: 
          { return symbol(sym.Eqv);
          }
        case 112: break;
        case 42: 
          { return symbol(sym.Imp);
          }
        case 113: break;
        case 43: 
          { return symbol(sym.For);
          }
        case 114: break;
        case 44: 
          { return symbol(sym.Sub);
          }
        case 115: break;
        case 45: 
          { return symbol(sym.Not);
          }
        case 116: break;
        case 46: 
          { return symbol(sym.Xor);
          }
        case 117: break;
        case 47: 
          { return symbol(sym.Case);
          }
        case 118: break;
        case 48: 
          { return symbol(sym.Char);
          }
        case 119: break;
        case 49: 
          { return symbol(sym.Else);
          }
        case 120: break;
        case 50: 
          { return symbol(sym.Exit);
          }
        case 121: break;
        case 51: 
          { return symbol(sym.TipoBoolean);
          }
        case 122: break;
        case 52: 
          { return symbol(sym.Loop);
          }
        case 123: break;
        case 53: 
          { return symbol(sym.Next);
          }
        case 124: break;
        case 54: 
          { return symbol(sym.Then);
          }
        case 125: break;
        case 55: 
          { return symbol(sym.While);
          }
        case 126: break;
        case 56: 
          { return symbol(sym.Float);
          }
        case 127: break;
        case 57: 
          { return symbol(sym.Print);
          }
        case 128: break;
        case 58: 
          { return symbol(sym.Double);
          }
        case 129: break;
        case 59: 
          { return symbol(sym.EndIf);
          }
        case 130: break;
        case 60: 
          { return symbol(sym.Select);
          }
        case 131: break;
        case 61: 
          { return symbol(sym.String);
          }
        case 132: break;
        case 62: 
          { return symbol(sym.Boolean);
          }
        case 133: break;
        case 63: 
          { return symbol(sym.EndFor);
          }
        case 134: break;
        case 64: 
          { return symbol(sym.ExitFor);
          }
        case 135: break;
        case 65: 
          { return symbol(sym.Integer);
          }
        case 136: break;
        case 66: 
          { return symbol(sym.Structs);
          }
        case 137: break;
        case 67: 
          { return symbol(sym.Private);
          }
        case 138: break;
        case 68: 
          { return symbol(sym.Ch);
          }
        case 139: break;
        case 69: 
          { return symbol(sym.Function);
          }
        case 140: break;
        case 70: 
          { return symbol(sym.EndWhile);
          }
        case 141: break;
        case 71: 
          { return symbol(sym.EndSelect);
          }
        case 142: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
